// Hardcoded tutorial data for the simulation
// Based on MainTest (1).json

export const TUTORIAL_CABLES = {
  PFP1: {
    id: "tut-pfp1",
    ribbonSize: 12,
    name: "PFP1",
    fiberCount: 432,
    type: "Feed" as const,
    parentCableId: null,
    spliceName: null,
  },
  PFP2: {
    id: "tut-pfp2",
    ribbonSize: 12,
    name: "PFP2",
    fiberCount: 432,
    type: "Feed" as const,
    parentCableId: null,
    spliceName: null,
  },
  d1: {
    id: "tut-d1",
    ribbonSize: 12,
    name: "d1",
    fiberCount: 24,
    type: "Distribution" as const,
    parentCableId: null,
    spliceName: null,
  },
  d2: {
    id: "tut-d2",
    ribbonSize: 12,
    name: "d2",
    fiberCount: 144,
    type: "Distribution" as const,
    parentCableId: null,
    spliceName: null,
  },
  d3: {
    id: "tut-d3",
    ribbonSize: 12,
    name: "d3",
    fiberCount: 216,
    type: "Distribution" as const,
    parentCableId: null,
    spliceName: "Print5.8",
  },
  d4: {
    id: "tut-d4",
    ribbonSize: 12,
    name: "d4",
    fiberCount: 48,
    type: "Distribution" as const,
    parentCableId: "tut-d3",
    spliceName: null,
  },
};

export const TUTORIAL_CIRCUITS = {
  // PFP1 circuit
  pfp1_pon: {
    id: "tut-c-pfp1-pon",
    cableId: "tut-pfp1",
    circuitId: "pon,1-432",
    position: 0,
    fiberStart: 1,
    fiberEnd: 432,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  // PFP2 circuit
  pfp2_pon: {
    id: "tut-c-pfp2-pon",
    cableId: "tut-pfp2",
    circuitId: "pon,433-864",
    position: 0,
    fiberStart: 1,
    fiberEnd: 432,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  // d1 circuits
  d1_pon: {
    id: "tut-c-d1-pon",
    cableId: "tut-d1",
    circuitId: "pon,1-12",
    position: 0,
    fiberStart: 1,
    fiberEnd: 12,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d1_a: {
    id: "tut-c-d1-a",
    cableId: "tut-d1",
    circuitId: "a,1-12",
    position: 1,
    fiberStart: 13,
    fiberEnd: 24,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  // d2 circuits
  d2_h: {
    id: "tut-c-d2-h",
    cableId: "tut-d2",
    circuitId: "h,37-96",
    position: 0,
    fiberStart: 1,
    fiberEnd: 60,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d2_pon: {
    id: "tut-c-d2-pon",
    cableId: "tut-d2",
    circuitId: "pon,13-48",
    position: 1,
    fiberStart: 61,
    fiberEnd: 96,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d2_d: {
    id: "tut-c-d2-d",
    cableId: "tut-d2",
    circuitId: "d,97-144",
    position: 2,
    fiberStart: 97,
    fiberEnd: 144,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  // d3 circuits
  d3_h: {
    id: "tut-c-d3-h",
    cableId: "tut-d3",
    circuitId: "h,1-24",
    position: 0,
    fiberStart: 1,
    fiberEnd: 24,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d3_pon429: {
    id: "tut-c-d3-pon429",
    cableId: "tut-d3",
    circuitId: "pon,429-432",
    position: 1,
    fiberStart: 25,
    fiberEnd: 28,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d3_pon433: {
    id: "tut-c-d3-pon433",
    cableId: "tut-d3",
    circuitId: "pon,433-584",
    position: 2,
    fiberStart: 29,
    fiberEnd: 180,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d3_a: {
    id: "tut-c-d3-a",
    cableId: "tut-d3",
    circuitId: "a,181-216",
    position: 3,
    fiberStart: 181,
    fiberEnd: 216,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  // d4 circuits (sub-splice of d3)
  d4_j: {
    id: "tut-c-d4-j",
    cableId: "tut-d4",
    circuitId: "j,29-48",
    position: 0,
    fiberStart: 1,
    fiberEnd: 20,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d4_pon429: {
    id: "tut-c-d4-pon429",
    cableId: "tut-d4",
    circuitId: "pon,429-432",
    position: 1,
    fiberStart: 21,
    fiberEnd: 24,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
  d4_pon433: {
    id: "tut-c-d4-pon433",
    cableId: "tut-d4",
    circuitId: "pon,433-456",
    position: 2,
    fiberStart: 25,
    fiberEnd: 48,
    isSpliced: 0 as 0 | 1,
    feedCableId: null,
    feedFiberStart: null,
    feedFiberEnd: null,
  },
};
